services:
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clustersim
    ports:
      - "3306:3306"
    networks:
      - clustersim

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-clustersim
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "80:80"
    networks:
      - clustersim
    depends_on:
      - database

  eurekaServer:
    image: eclipse-temurin:21-jre
    container_name: eureka-server
    volumes:
      - ./EurekaServer/target/EurekaServer-0.0.1-SNAPSHOT.war:/app.war
    working_dir: /app
    command: ["java", "-jar", "/app.war"]
    ports:
      - "8761:8761"
    networks:
      - clustersim

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - clustersim

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - clustersim

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - clustersim
    depends_on:
      - apiGateway

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - clustersim
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

  apiGateway:
    image: eclipse-temurin:21-jre
    volumes:
      - ./ApiGateway/target/ApiGateway-0.0.1-SNAPSHOT.war:/app.war
    working_dir: /app
    command: ["java", "-jar", "/app.war"]
    networks:
      - clustersim
    ports:
      - "8080:8080"
    depends_on:
      - eurekaServer

  authenticationMicroservice:
    image: eclipse-temurin:21-jre
    volumes:
      - ./AuthenticationMicroservice/target/AuthenticationMicroservice-0.0.1-SNAPSHOT.war:/app.war
    working_dir: /app
    command: ["java", "-jar", "/app.war"]
    networks:
      - clustersim
    depends_on:
      - eurekaServer
      - database
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  documentLoaderMicroservice:
    image: eclipse-temurin:21-jre
    volumes:
      - ./DocumentLoaderMicroservice/target/DocumentLoaderMicroservice-0.0.1-SNAPSHOT.war:/app.war
      - ./DocumentLoaderMicroservice/documents:/app/documents
    working_dir: /app
    command: ["java", "-jar", "/app.war"]
    networks:
      - clustersim
    depends_on:
      - eurekaServer
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

networks:
  clustersim:
    name: clustersim
    driver: bridge

volumes:
  grafana-data:
