services:

  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clustersim
    ports:
      - "3306:3306"
    networks:
      - clustersim

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-clustersim
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "80:80"
    networks:
      - clustersim
    depends_on:
      - database

networks:
  clustersim:
    name: clustersim
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

# docker-compose up
# oppure in modalità detatched per non bloccare il terminale
# docker-compose up -d